name: Inject Secret and Deploy

on:
  push:
    branches:
      - main  # Asegúrate de que este sea el nombre de tu rama

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Esta es la parte que faltaba y que causa el error en la imagen
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace API Key
        run: |
          sed -i "s/VALUE_TO_REPLACE/${{ secrets.OPENWEATHER_API_KEY }}/g" index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
